### MODULE SECTION START ###
sounds,Dono
		<sounds name="Dono">
      <sound>sound\sndSonicFound</sound>
      <sound>sound\sndSonicHello</sound>
      <sound>sound\sndSonicSlow</sound>
      <sound>sound\exe</sound>
    </sounds>### MODULE SECTION START ###
sprites,Dono
		<sprites name="Dono">
      <sprites name="Killers">
        <sprite>sprites\sprDonoSpikeUp</sprite>
        <sprite>sprites\sprDonoSpikeDown</sprite>
        <sprite>sprites\sprDonoSpikeLeft</sprite>
        <sprite>sprites\sprDonoSpikeRight</sprite>
        <sprite>sprites\sprDonoMiniUp</sprite>
        <sprite>sprites\sprDonoMiniDown</sprite>
        <sprite>sprites\sprDonoMiniLeft</sprite>
        <sprite>sprites\sprDonoMiniRight</sprite>
      </sprites>
      <sprites name="EXE">
        <sprite>sprites\sprDonoExeSpikeUp</sprite>
        <sprite>sprites\sprDonoExeSpikeDown</sprite>
        <sprite>sprites\sprDonoExeSpikeLeft</sprite>
        <sprite>sprites\sprDonoExeSpikeRight</sprite>
        <sprite>sprites\sprDonoExeTorch</sprite>
        <sprite>sprites\sprDonoExeTorchOff</sprite>
        <sprite>sprites\sprDonoExeGOD</sprite>
      </sprites>
      <sprite>sprites\sprDonoPlatform</sprite>
      <sprite>sprites\sprDonoSidewaysPlatform</sprite>
      <sprite>sprites\sprDonoSidewaysPlatform2</sprite>
      <sprite>sprites\sprDonoSave</sprite>
      <sprite>sprites\sprDonoSave2</sprite>
      <sprite>sprites\sprDonoPlatformKiller</sprite>
      <sprite>sprites\sprDonoArtwork</sprite>
      <sprite>sprites\sprDonoThanks</sprite>
      <sprite>sprites\sprDonoLight</sprite>
      <sprite>sprites\sprDonoCat</sprite>
    </sprites>### MODULE SECTION START ###
objects,Dono
		<objects name="Dono">
      <object>objects\objDonoBlockNoCollision</object>
      <object>objects\objDonoSave</object>
      <object>objects\objDonoSave2</object>
      <object>objects\objDonoWarp</object>
      <object>objects\objDonoWarpNext</object>
      <object>objects\objFieldDotkidOff</object>
      <object>objects\objFieldDotkidOn</object>
      <object>objects\object184</object>
      <object>objects\object105</object>
      <objects name="Platforms WHY">
        <object>objects\objDonoNoCollisionPlatform</object>
        <object>objects\objDonoMovingPlatform</object>
        <object>objects\objDonoMovingPlatformNoCollision</object>
        <object>objects\objDonoMovingPlatformNoBounce</object>
        <object>objects\objDonoBlockRise</object>
        <object>objects\objDonoRisingSidewaysPlatformNoCollision</object>
        <object>objects\obDonojBlockFall</object>
        <object>objects\objDonoSidewaysPlatform</object>
        <object>objects\objDonoMovingPlatformHoriNoCollision</object>
        <object>objects\objMovingPlatformHoriNoCollision2</object>
        <object>objects\objDonoMovingPlatformHoriNoCollision2</object>
        <object>objects\objDonoMovingPlatformHoriNoCollision3</object>
      </objects>
      <objects name="Killers">
        <object>objects\objDonoSpikeUp</object>
        <object>objects\objDonoSpikeRight</object>
        <object>objects\objDonoSpikeLeft</object>
        <object>objects\objDonoSpikeDown</object>
        <object>objects\objDonoMiniUp</object>
        <object>objects\objDonoMiniRight</object>
        <object>objects\objDonoMiniLeft</object>
        <object>objects\objDonoMiniDown</object>
        <object>objects\objDonoCherry</object>
        <object>objects\objDonoCherryBounce</object>
        <object>objects\objDonoCherryBounceRandom</object>
        <object>objects\objDonoCherryBounceLat</object>
        <object>objects\objDonoCherryBounceVert</object>
        <object>objects\objDonoKillerBlock</object>
        <object>objects\objFunny</object>
        <object>objects\object96</object>
      </objects>
      <objects name="exe">
        <object>objects\objExePlayerStart</object>
        <object>objects\object101</object>
        <object>objects\object102</object>
        <object>objects\object103</object>
        <object>objects\object104</object>
        <object>objects\objExeTorch</object>
        <object>objects\objLighting</object>
        <object>objects\objIAMGOD</object>
      </objects>
      <object>objects\objDonoCatSpin</object>
    </objects>### MODULE SECTION START ###
rooms,Dono
		<rooms name="Dono">
      <room>rooms\rDono_Intro</room>
      <room>rooms\rDono_01</room>
      <room>rooms\rDono_02</room>
      <room>rooms\rDono_03</room>
      <room>rooms\rDono_04</room>
      <room>rooms\rDono_05</room>
      <room>rooms\rDono_06</room>
      <room>rooms\rDono_07</room>
      <room>rooms\rDono_08</room>
      <room>rooms\rDonoEnd</room>
      <room>rooms\rDonoExeEntrance</room>
      <room>rooms\rDonoLoser</room>
      <room>rooms\rCum_demon</room>
      <room>rooms\room20</room>
      <rooms name="exe">
        <room>rooms\room18</room>
        <room>rooms\room19</room>
        <room>rooms\room21</room>
        <room>rooms\room22</room>
        <room>rooms\room23</room>
      </rooms>
    </rooms>